theme = "gruvbox"

[keys.normal]
"A-left" = "jump_view_left"
"A-right" = "jump_view_right"
"A-up" = "jump_view_up"
"A-down" = "jump_view_down"

[editor]
auto-pairs = false
color-modes = true
rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "file-name",
  "spacer",
  "read-only-indicator",
  "file-modification-indicator",
  "spacer",
]

[editor.statusline.mode]
insert = "INSERT"
normal = "NORMAL"
select = "SELECT"

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.indent-guides]
render = true
skip-levels = 1
