[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = 'prettier', args = ["--parser", "yaml"] }
auto-format = true

[[language]]
name = "astro"
language-servers = ["astro-ls"]
roots = ["package.json", "astro.config.mjs"]
formatter = { command = "prettier", args = [
  "--plugin",
  "prettier-plugin-astro",
  "--parser",
  "astro",
] }
auto-format = true

[language-server.astro-ls]
args = ["--stdio"]
command = "astro-ls"
# TODO: bad path
config = { typescript = { tsdk = "/opt/homebrew/Cellar/typescript/5.6.2/libexec/lib/node_modules/typescript/lib" } }

[[language]]
name = "svelte"
language-servers = [
  "svelteserver",
  "vscode-eslint-language-server",
  "tailwindcss-ls",
]
formatter = { command = "prettier", args = [
  "--plugin",
  "prettier-plugin-svelte",
  "--plugin",
  "prettier-plugin-tailwindcss",
  "--parser",
  "svelte",
] }
auto-format = true

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "lua"
formatter = { command = "stylua", args = ["-"] }
auto-format = true

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "cmake"
formatter = { command = "gersemi", args = ["-"] }
auto-format = true

[[language]]
name = "gdscript"
language-servers = ["godot"]

[language-server.godot]
command = "nc"
args = ["localhost", "6005"]

[[language]]
name = "typst"
language-servers = ["tinymist", "vale-ls"]
formatter = { command = "typstyle" }
auto-format = true

[[language]]
name = "go"
formatter = { command = "gofumpt" }
