[[language]]
auto-format = true
formatter = { command = "prettier", args = [
  "--plugin",
  "prettier-plugin-astro",
  "--parser",
  "astro",
] }
language-servers = ["astro-ls"]
name = "astro"
roots = ["package.json", "astro.config.mjs"]

[language-server.astro-ls]
args = ["--stdio"]
command = "astro-ls"
# TODO: bad path
config = { typescript = { tsdk = "/opt/homebrew/Cellar/typescript/5.6.2/libexec/lib/node_modules/typescript/lib" } }

[[language]]
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }
language-servers = ["pyright", "ruff"]
name = "python"

[language-server.ruff]
args = ["server"]
command = "ruff"

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[[language]]
auto-format = true
formatter = { command = "taplo", args = ["format", "-"] }
name = "toml"

[[language]]
formatter = { command = 'prettier', args = ["--parser", "html"] }
name = "html"

[[language]]
formatter = { command = 'prettier', args = ["--parser", "json"] }
name = "json"

[[language]]
formatter = { command = 'prettier', args = ["--parser", "css"] }
name = "css"

[[language]]
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
name = "javascript"

[[language]]
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
name = "typescript"

[[language]]
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
name = "jsx"

[[language]]
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
name = "tsx"

[[language]]
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "yaml"] }
name = "yaml"
