start-at-login = true

[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.left = 5
outer.bottom = 5
outer.top = 5
outer.right = 5

[mode.main.binding]
cmd-up = 'focus up'
cmd-down = 'focus down'
cmd-left = 'focus left'
cmd-right = 'focus right'

cmd-shift-up = 'move up'
cmd-shift-down = 'move down'
cmd-shift-left = 'move left'
cmd-shift-right = 'move right'

ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'
ctrl-0 = 'workspace 10'

ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-5 = 'move-node-to-workspace 5'
ctrl-shift-6 = 'move-node-to-workspace 6'
ctrl-shift-7 = 'move-node-to-workspace 7'
ctrl-shift-8 = 'move-node-to-workspace 8'
ctrl-shift-9 = 'move-node-to-workspace 9'
ctrl-shift-0 = 'move-node-to-workspace 10'

alt-ctrl-space = 'mode service'

[mode.service.binding]
t = ['layout tiles horizontal vertical', 'mode main']
shift-t = ['layout accordion horizontal vertical', 'mode main']
c = ['reload-config', 'mode main']
f = ['layout floating tiling', 'mode main']
esc = 'mode main'

[workspace-to-monitor-force-assignment]
10 = 'secondary'

[[on-window-detected]]
if.window-title-regex-substring = '\(DEBUG\)'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.FaceTime'
run = ['layout floating']
