"j" = "next"
"<down>" = "next"
"k" = "prev"
"<up>" = "prev"
"S-j" = "move-next"
"S-<down>" = "move-next"
"S-k" = "move-prev"
"S-<up>" = "move-prev"
"q" = "quit"
"S-q" = "abort"
"o" = "go-to-parent"
"h" = "go-to-parent"
"<left>" = "go-to-parent"
"<ret>" = "enter-dir"
"l" = "enter-dir"
"<right>" = "enter-dir"
"<spc>" = "toggle-select"
"<tab>" = "cycle"
"." = "hide-show"
"/" = "filter"
