declare-option -hidden bool init_done
evaluate-commands %sh{
    $kak_opt_init_done && exit
    echo 'source ~/.config/kak/once.kak'
}
set-option global init_done true

evaluate-commands %sh{
    rc_files=$(fd --extension kak . $HOME/.config/kak/conf.d)
    for file in $rc_files; do
        echo "source $file"
    done
}

define-command -override config-reload %{
    source ~/.config/kak/kakrc
}

set-option global startup_info_version 20250603
set-option global ui_options \
  terminal_set_title=false \
  terminal_assistant=none

set-option global tabstop 4
set-option global modelinefmt '{{mode_info}} {Path}%val{bufname}{StatusLine} %val{cursor_line}:%val{cursor_char_column} {{context_info}}'
