declare-option -hidden bool init_done
evaluate-commands %sh{
    $kak_opt_init_done && exit
    echo 'source ~/.config/kak/once.kak'
}
set-option global init_done true

evaluate-commands %sh{
    rc_files=$(fd --extension kak . $HOME/.config/kak/conf.d)
    for file in $rc_files; do
        echo "source $file"
    done
}



